name: "Member: Add person"
description: "Propose a new member card"
labels: ["member"]
title: "Add member: <full-name>"
body:
  - type: markdown
    attributes:
      value: |
        You can either fill the fields below or paste a YAML block:

        ```yaml
        name: "Jane Doe"
        role: "PhD Student"
        affiliation: "Cornell Tech"
        image: "https://example.com/avatar.jpg" # or ../../assets/members/jane-doe.jpg
        website: "https://example.com"
        order: 10
        tags: [member]
        ```
  - type: input
    id: name
    attributes:
      label: Full name
    validations:
      required: true
  - type: input
    id: role
    attributes:
      label: Role (optional)
  - type: input
    id: affiliation
    attributes:
      label: Affiliation (optional)
  - type: input
    id: image
    attributes:
      label: Image URL (optional)
      description: "Remote URL (downloaded automatically) or repo path under src/assets/members"
  - type: input
    id: website
    attributes:
      label: Website (optional)
  - type: input
    id: order
    attributes:
      label: Order (optional)
      placeholder: "0"
  - type: textarea
    id: tags
    attributes:
      label: Tags (optional)
      description: "Comma-separated or YAML array"

