name: "Reading List: Add paper"
description: "Propose a paper (by DOI) for the Reading List"
labels: ["reading-list"]
title: "Add reading: <short-title-or-doi>"
body:
  - type: markdown
    attributes:
      value: |
        Please provide the DOI. Title/authors/venue/year can be omitted; the bot will resolve via Crossref.
  - type: input
    id: doi
    attributes:
      label: DOI
      description: "Provide the DOI (e.g., 10.1145/3640792.3675740)"
      placeholder: "10.1145/xxxx/yyyy"
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title (optional)
  - type: textarea
    id: authors
    attributes:
      label: Authors (optional)
      description: "Comma-separated list (e.g., Jane Doe, John Smith)"
  - type: input
    id: venue
    attributes:
      label: Venue (optional)
  - type: input
    id: year
    attributes:
      label: Year (optional)
      placeholder: "2025"
  - type: input
    id: url
    attributes:
      label: URL (optional)
      placeholder: "https://example.com/paper"
  - type: markdown
    attributes:
      value: |
        Example body the workflow understands:

        ```
        ### DOI
        10.1145/3640792.3675740

        ### Title (optional)
        A cool paper

        ### Authors (optional)
        Jane Doe, John Smith

        ### Venue (optional)
        FOO'25

        ### Year (optional)
        2025

        ### URL (optional)
        https://doi.org/10.1145/3640792.3675740
        ```
  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: "Any extra context for reviewers"

